// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqoM5q3zEkFRiaUXIVIutzq3Xg7VQS14I',
    appId: '1:543410368633:web:434b99a9f315df975b64a8',
    messagingSenderId: '543410368633',
    projectId: 'modifai0127',
    authDomain: 'modifai0127.firebaseapp.com',
    storageBucket: 'modifai0127.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDItXslqlHw1-pvPo30vcgfqNru5VlT6ss',
    appId: '1:543410368633:android:d6b0d4a9793c73db5b64a8',
    messagingSenderId: '543410368633',
    projectId: 'modifai0127',
    storageBucket: 'modifai0127.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqRpdcmcCDmgJZMwfmnj3voImReqClVF0',
    appId: '1:543410368633:ios:5a47d0ccdfe588dd5b64a8',
    messagingSenderId: '543410368633',
    projectId: 'modifai0127',
    storageBucket: 'modifai0127.firebasestorage.app',
    iosClientId: '543410368633-o8c9vv0r92robbpu2fkgna1ofavvmrrs.apps.googleusercontent.com',
    iosBundleId: 'com.example.modifai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqRpdcmcCDmgJZMwfmnj3voImReqClVF0',
    appId: '1:543410368633:ios:5a47d0ccdfe588dd5b64a8',
    messagingSenderId: '543410368633',
    projectId: 'modifai0127',
    storageBucket: 'modifai0127.firebasestorage.app',
    iosClientId: '543410368633-o8c9vv0r92robbpu2fkgna1ofavvmrrs.apps.googleusercontent.com',
    iosBundleId: 'com.example.modifai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqoM5q3zEkFRiaUXIVIutzq3Xg7VQS14I',
    appId: '1:543410368633:web:ad27387cf1da2fda5b64a8',
    messagingSenderId: '543410368633',
    projectId: 'modifai0127',
    authDomain: 'modifai0127.firebaseapp.com',
    storageBucket: 'modifai0127.firebasestorage.app',
  );
}
